exp_name: gycbv
debug: false
cache_dir: '.cache'
obj_ids:
- 1
sym_aware: true
dataloader:
  num_workers: 8
  batch_size: 32
train:
  num_epochs: 20
  test_every: 4
optimizer:
  type: Ranger
  lr: 0.0002
  wd: 0.0001
scheduler:
  name: flat_and_anneal
  anneal_method: cosine
  warmup_method: linear
  anneal_point: 0.72
  rel_steps:
  - 0.5
  - 0.75
  warmup_factor: 0.001
  warmup_iters: 1000
  step_gamma: 0.5
pnp_solver:
  dense_point_select: quantile
  quantile: 0.3
  solvers:
  - weighted
train_dataset:
  name: ycbvposecnn
  bg_dir: datasets/VOCdevkit/VOC2012/JPEGImages
  dataset_root: datasets/BOP_DATASETS/ycbv
  list_files:
  - assets/image_lists/ycbv/train_pbr.txt
  - assets/image_lists/ycbv/train_real.txt
  net_input_wh:
  - 256
  - 256
  net_output_wh:
  - 64
  - 64
  pixel_aug_prob: 0.8
  rotate_prob: 1
  switch_bg_prob: 0.5
  visib_frac: 0.3
  dzi_scale_ratio: 0.25
  dzi_shift_ratio: 0.25
  dzi_pad_scale: 1.5
test_dataset:
  name: ycbvposecnn
  dataset_root: datasets/BOP_DATASETS/ycbv
  detection: assets/detection_results/ycbv/fcos_V57eSE_MSx1333_ColorAugAAEWeaker_8e_ycbv_real_pbr_8e_test_keyframe.json
  visib_frac: 0.0
  list_files:
  - assets/image_lists/ycbv/test.txt
  net_input_wh:
  - 256
  - 256
  net_output_wh:
  - 64
  - 64
  dzi_pad_scale: 1.5
model:
  net_name: cdpn_resnet
  net_config:
    back_layers_num: 34
    concat: false
loss:
  pose_loss_cfg:
    clip_weight_grad: true
  pose_loss_start_step: 2000
  pose_loss_start_epoch: 1
  w_loss_pose: 0.02
  w_loss_seg: 0.25
  w_loss_noc: 1